"""
Seed 10 fake founder profiles into Firestore for demo purposes.
Run: python seed_founders.py
"""
import os
import firebase_admin
from firebase_admin import credentials, firestore
from dotenv import load_dotenv

load_dotenv()

service_account_path = os.getenv("FIREBASE_SERVICE_ACCOUNT_PATH", "./serviceAccountKey.json")
if not firebase_admin._apps:
    cred = credentials.Certificate(service_account_path)
    firebase_admin.initialize_app(cred)

db = firestore.client()

FOUNDERS = [
    {
        "uid": "seed_alice_01",
        "name": "Alice Chen",
        "email": "alice@demo.com",
        "photoURL": "",
        "bio": "Ex-Google ML engineer building AI tools for healthcare",
        "linkedin": "",
        "location": "San Francisco, CA",
        "skills": ["Technical", "AI/ML", "Product"],
        "interests": ["Healthtech", "AI Tools", "SaaS"],
        "ideaStage": "clear",
        "commitmentLevel": "Full-time",
        "targetBatch": "W26",
        "lookingFor": ["Business", "Sales"],
        "startupIdea": "AI-powered diagnostic assistant for rural clinics that reduces misdiagnosis by 40%.",
        "biggestStrength": "Deep expertise in ML model deployment and 5 years at Google Health.",
        "connections": [],
        "pendingRequests": [],
        "incomingRequests": [],
    },
    {
        "uid": "seed_bob_02",
        "name": "Bob Martinez",
        "email": "bob@demo.com",
        "photoURL": "",
        "bio": "Serial entrepreneur, sold my last edtech startup for $2M",
        "linkedin": "",
        "location": "Austin, TX",
        "skills": ["Business", "Sales", "Marketing"],
        "interests": ["Edtech", "SaaS", "B2B"],
        "ideaStage": "clear",
        "commitmentLevel": "Full-time",
        "targetBatch": "W26",
        "lookingFor": ["Technical", "AI/ML"],
        "startupIdea": "Adaptive learning platform that personalizes curriculum using GPT for K-12 schools.",
        "biggestStrength": "Domain expertise in education sales and strong school district relationships.",
        "connections": [],
        "pendingRequests": [],
        "incomingRequests": [],
    },
    {
        "uid": "seed_carol_03",
        "name": "Carol Kim",
        "email": "carol@demo.com",
        "photoURL": "",
        "bio": "Fintech PM at Stripe, passionate about financial inclusion",
        "linkedin": "",
        "location": "New York, NY",
        "skills": ["Product", "Finance", "Business"],
        "interests": ["Fintech", "Consumer Apps", "SaaS"],
        "ideaStage": "rough",
        "commitmentLevel": "Full-time",
        "targetBatch": "S26",
        "lookingFor": ["Technical", "Design"],
        "startupIdea": "Neobank for gig workers with instant payouts and micro-investing.",
        "biggestStrength": "4 years at Stripe building payment infrastructure and deep fintech network.",
        "connections": [],
        "pendingRequests": [],
        "incomingRequests": [],
    },
    {
        "uid": "seed_david_04",
        "name": "David Okonkwo",
        "email": "david@demo.com",
        "photoURL": "",
        "bio": "Full-stack dev and open source contributor, React + Python",
        "linkedin": "",
        "location": "London, UK",
        "skills": ["Technical", "Design", "Product"],
        "interests": ["Developer Tools", "SaaS", "AI Tools"],
        "ideaStage": "looking",
        "commitmentLevel": "Full-time",
        "targetBatch": "W26",
        "lookingFor": ["Business", "Marketing"],
        "startupIdea": "",
        "biggestStrength": "Can ship fast — built 3 products from 0 to 10K users as a solo dev.",
        "connections": [],
        "pendingRequests": [],
        "incomingRequests": [],
    },
    {
        "uid": "seed_emma_05",
        "name": "Emma Patel",
        "email": "emma@demo.com",
        "photoURL": "",
        "bio": "Climate scientist turned founder, MIT PhD in atmospheric systems",
        "linkedin": "",
        "location": "Boston, MA",
        "skills": ["Technical", "Operations", "AI/ML"],
        "interests": ["Climate", "Deep Tech", "B2B"],
        "ideaStage": "clear",
        "commitmentLevel": "Full-time",
        "targetBatch": "S26",
        "lookingFor": ["Business", "Finance"],
        "startupIdea": "Carbon accounting platform for SMBs using satellite data and ML.",
        "biggestStrength": "Published 12 papers on emissions modeling, strong academic network.",
        "connections": [],
        "pendingRequests": [],
        "incomingRequests": [],
    },
    {
        "uid": "seed_frank_06",
        "name": "Frank Liu",
        "email": "frank@demo.com",
        "photoURL": "",
        "bio": "YC alum (S22), building my second startup in AI infrastructure",
        "linkedin": "",
        "location": "San Francisco, CA",
        "skills": ["Technical", "Product", "AI/ML"],
        "interests": ["AI Tools", "Developer Tools", "Deep Tech"],
        "ideaStage": "clear",
        "commitmentLevel": "Full-time",
        "targetBatch": "W26",
        "lookingFor": ["Business", "Sales"],
        "startupIdea": "LLM observability platform — like Datadog for AI applications.",
        "biggestStrength": "Been through YC once, know the process, and have investor relationships.",
        "connections": [],
        "pendingRequests": [],
        "incomingRequests": [],
    },
    {
        "uid": "seed_grace_07",
        "name": "Grace Thompson",
        "email": "grace@demo.com",
        "photoURL": "",
        "bio": "UX designer & front-end dev, prev at Figma and Airbnb",
        "linkedin": "",
        "location": "Seattle, WA",
        "skills": ["Design", "Technical", "Product"],
        "interests": ["Consumer Apps", "E-commerce", "SaaS"],
        "ideaStage": "rough",
        "commitmentLevel": "Part-time",
        "targetBatch": "W26",
        "lookingFor": ["Business", "Marketing", "Sales"],
        "startupIdea": "Social commerce platform where creators build shoppable storefronts.",
        "biggestStrength": "Eye for design that converts — increased Airbnb booking flow by 18%.",
        "connections": [],
        "pendingRequests": [],
        "incomingRequests": [],
    },
    {
        "uid": "seed_hassan_08",
        "name": "Hassan Ahmed",
        "email": "hassan@demo.com",
        "photoURL": "",
        "bio": "Ex-McKinsey consultant specializing in healthcare strategy",
        "linkedin": "",
        "location": "Chicago, IL",
        "skills": ["Business", "Operations", "Finance"],
        "interests": ["Healthtech", "B2B", "SaaS"],
        "ideaStage": "rough",
        "commitmentLevel": "Full-time",
        "targetBatch": "S26",
        "lookingFor": ["Technical", "AI/ML"],
        "startupIdea": "Workflow automation for hospital admin that saves 20 hours per week.",
        "biggestStrength": "Deep understanding of healthcare operations and payor systems.",
        "connections": [],
        "pendingRequests": [],
        "incomingRequests": [],
    },
    {
        "uid": "seed_iris_09",
        "name": "Iris Nakamura",
        "email": "iris@demo.com",
        "photoURL": "",
        "bio": "Growth marketer, scaled 3 startups from 0 to $1M ARR",
        "linkedin": "",
        "location": "Los Angeles, CA",
        "skills": ["Marketing", "Sales", "Business"],
        "interests": ["E-commerce", "Consumer Apps", "Gaming"],
        "ideaStage": "looking",
        "commitmentLevel": "Full-time",
        "targetBatch": "W26",
        "lookingFor": ["Technical", "Design"],
        "startupIdea": "",
        "biggestStrength": "Proven growth playbook — SEO, paid, and viral loops.",
        "connections": [],
        "pendingRequests": [],
        "incomingRequests": [],
    },
    {
        "uid": "seed_james_10",
        "name": "James Park",
        "email": "james@demo.com",
        "photoURL": "",
        "bio": "Backend engineer at Meta, passionate about developer experience",
        "linkedin": "",
        "location": "Menlo Park, CA",
        "skills": ["Technical", "Product", "Operations"],
        "interests": ["Developer Tools", "AI Tools", "SaaS"],
        "ideaStage": "clear",
        "commitmentLevel": "Part-time",
        "targetBatch": "S26",
        "lookingFor": ["Business", "Marketing"],
        "startupIdea": "AI code review tool that catches bugs before CI — faster than humans.",
        "biggestStrength": "Built internal dev tools used by 10K+ engineers at Meta.",
        "connections": [],
        "pendingRequests": [],
        "incomingRequests": [],
    },
]


def main():
    print("🌱 Seeding 10 founder profiles to Firestore...")
    for f in FOUNDERS:
        db.collection("users").document(f["uid"]).set(f)
        print(f"  ✅ {f['name']} ({f['uid']})")
    print(f"\n🎉 Done! {len(FOUNDERS)} founders seeded.")


if __name__ == "__main__":
    main()
